parser: babel-eslint
extends:
  - airbnb
  - prettier
  - plugin:prettier/recommended
plugins:
  - prettier
overrides:
  - files: '**/*.coffee'
    parser: eslint-plugin-coffee
    plugins:
      - coffee
    extends:
      - plugin:coffee/airbnb
      - plugin:coffee/import
    settings:
      import/parsers:
        eslint-plugin-coffee/lib/parser: ['.coffee']
        babel-eslint: ['.js', '.jsx']
